### PR TITLE
Fix title casing

### PR DESCRIPTION
**Pull request by fh**

### CODE REVIEW

**Comment by walski** [comment]
cite-proc had a problem "counting" words in a string when looking for capitalization of them.

The rule that it tried to model is: "Capitalize all words if they are not a stopword or if they are the first word".

What cite-proc actually did: "Capitalize all words if they are not a stopword or if they are the first **lower letter** word."

So I changed the regex to match not only words starting with a lower letter but matching all words. This way I can determine the first word correctly and I just moved the "lower letter" check that was in the surrounding regex into it's separate check inside of the ``gsub!`` block.

**Comment by walski** [comment]
The latest fix also makes the errors in ``csl-ruby``'s MLA8 branch go down from 18 to 11. Still working on the rest of it.

**Comment by walski** [comment]
Arg, it seems that this now capitalizes URLs like: ``easybib.com`` to ``easybib.Com``.

**Comment by walski** [comment]
This should be merge-able, now @fh :)

**Comment by fh** [comment]
Not deleting the branch - guess we want to PR this to upstream, too?

**Pull request merged**
